version: '3.8'

services:

  app:
    image: 'hrm-app'
    build: ./app
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/hrm
      - SPRING_DATASOURCE_USERNAME=hrm-user
      - SPRING_DATASOURCE_PASSWORD=hrm-password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"

  db:
    image: 'postgres:15-alpine'
    container_name: db
    environment:
      - POSTGRES_DB=hrm
      - POSTGRES_USER=hrm-user
      - POSTGRES_PASSWORD=hrm-password

  client:
    image: 'hrm-client'
    container_name: client
    build: ./client
    volumes:
      - './client:/usr/src/client'
    ports:
      - '4200:4200'
    command: >
      bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"
