spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hrm
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    database: postgresql
    properties:
      hibernate:
        format_sql: true